[package]
name = "water-bears"
version = "0.0.1"
edition = "2021"
resolver = "2"

[dependencies]
chrono = "0.4.38"
sbor = { version = "1.2.0" }
scrypto = { version = "1.2.0" }

[dev-dependencies]
radix-engine = { version = "1.2.0" }
scrypto-test = { version = "1.2.0" }
radix-engine-interface = { version = "1.2.0" }
water-bears = { path = ".", features = ["test"] }

[features]
default = []
test = []

[profile.release]
opt-level = 'z'        # Optimize for size.
lto = true             # Enable Link Time Optimization.
codegen-units = 1      # Reduce number of codegen units to increase optimizations.
panic = 'abort'        # Abort on panic.
strip = true           # Strip the symbols.
overflow-checks = true # Panic in the case of an overflow.

[lib]
crate-type = ["cdylib", "lib"]

[workspace]
# Set the package crate as its own empty workspace, to hide it from any potential ancestor workspace
# Remove this [workspace] section if you intend the package to be part of a Cargo workspace